In [1]:
import cv2
import numpy as np
from keras import Sequential
from keras.layers import Dense, Conv2D, Dropout, MaxPooling2D, Flatten
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.preprocessing.image import ImageDataGenerator

C:\Users\shuoh\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


## 將訓練資料匯入

In [2]:
import os
ng2 = os.listdir("IC2/ng2")
ok2 = os.listdir("IC2/ok2")
ng1 = os.listdir("IC1/ng")
ok1 = os.listdir("IC1/ok")
ok2_gen = os.listdir("IC2/ok2_gen")
ng2_gen = os.listdir("IC2/ng2_gen")

img_ng2=[]
img_ng1=[]
img_ok2=[]
img_ok1=[]

for img in ng2:
    ng = cv2.imread("IC2/ng2/"+img)
    ng = cv2.resize(ng, (160,112), interpolation=cv2.INTER_AREA)
#     ng = ng.resize()
#     print(ng)
    img_ng2.append(ng)
for img in ng2_gen:
    ng = cv2.imread("IC2/ng2_gen/"+img)
    ng = cv2.resize(ng, (160,112), interpolation=cv2.INTER_AREA)

#     ng = ng.resize()
#     print(ng)
    img_ng2.append(ng)
img_ng2 = np.array(img_ng2)
print('image in ng2:',img_ng2.shape)

for img in ng1:
    ng = cv2.imread("IC1/ng/"+img)
    ng = cv2.resize(ng, (160,112), interpolation=cv2.INTER_AREA)

#     print(ng)
    img_ng1.append(ng)
img_ng1 = np.array(img_ng1)
print('image in ng1:',img_ng1.shape)


for img in ok2:
    ng = cv2.imread("IC2/ok2/"+img)
    ng = cv2.resize(ng, (160,112), interpolation=cv2.INTER_AREA)

#     print(ng)
    img_ok2.append(ng)
for img in ok2_gen:
    ng = cv2.imread("IC2/ok2_gen/"+img)
    ng = cv2.resize(ng, (160,112), interpolation=cv2.INTER_AREA)

#     print(ng)
    img_ok2.append(ng)
img_ok2 = np.array(img_ok2)
print('image in ok2:',img_ok2.shape)

i=0
for img in ok1:
    
    while i<1001:
        i+=1
        ng = cv2.imread("IC1/ok/"+img)
        ng = cv2.resize(ng, (160,112), interpolation=cv2.INTER_AREA)

#     print(ng)
        img_ok1.append(ng)
img_ok1 = np.array(img_ok1)
print('image in ok1:',img_ok1.shape)

image in ng2: (228, 112, 160, 3)
image in ng1: (926, 112, 160, 3)
image in ok2: (252, 112, 160, 3)
image in ok1: (1001, 112, 160, 3)


In [3]:
# # # print(img_ng2[0])
# # print(img_ng2[0].shape)
# # a = cv2.resize(img_ng2[0], (300,100))
# # print(a.shape)
# a = img_ng2[0]
# # a = np.reshape(a, (300,100))
# cv2.imshow("img",a)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# # print(a.shape)


製作one hot格式的label

In [4]:
img_ng2_label=[]
for i in img_ng2:
    img_ng2_label.append([1,0])
img_ng2_label = np.array(img_ng2_label)
print(img_ng2_label.shape)
img_ng1_label=[]
for i in img_ng1:
    img_ng1_label.append([1,0])
img_ng1_label = np.array(img_ng1_label)
print(img_ng1_label.shape)
img_ok2_label=[]
for i in img_ok2:
    img_ok2_label.append([0,1])
img_ok2_label = np.array(img_ok2_label)
print(img_ok2_label.shape)
img_ok1_label=[]
for i in img_ok1:
    img_ok1_label.append([0,1])
img_ok1_label = np.array(img_ok1_label)
print(img_ok1_label.shape)

(228, 2)
(926, 2)
(252, 2)
(1001, 2)


## 照片預處理()

1.灰階

In [5]:
gray_ng2=[]
gray_ng1=[]
gray_ok2=[]
gray_ok1=[]

for img in img_ng2:
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray_ng2.append(gray)
gray_ng2 = np.array(gray_ng2)
# gray_ng2 = np.reshape(gray_ng2, (57,247,363,1))
print(gray_ng2.shape)
for img in img_ng1:
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray_ng1.append(gray)
gray_ng1 = np.array(gray_ng1)
# gray_ng1 = np.reshape(gray_ng1, (57,247,363,1))
print(gray_ng1.shape)
for img in img_ok2:
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray_ok2.append(gray)
gray_ok2 = np.array(gray_ok2)
# gray_ng2 = np.reshape(gray_ng2, (57,247,363,1))
print(gray_ok2.shape)
for img in img_ok1:
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray_ok1.append(gray)
gray_ok1 = np.array(gray_ok1)
# gray_ng2 = np.reshape(gray_ng2, (57,247,363,1))
print(gray_ok1.shape)

(228, 112, 160)
(926, 112, 160)
(252, 112, 160)
(1001, 112, 160)


2.正規化

In [6]:
gray_ng2=gray_ng2/255
gray_ng1=gray_ng1/255
gray_ok2=gray_ok2/255
gray_ok1=gray_ok1/255
print(gray_ng2[0])

[[0.17647059 0.18039216 0.18431373 ... 0.17647059 0.18039216 0.18431373]
 [0.18039216 0.18039216 0.18039216 ... 0.17647059 0.18039216 0.18823529]
 [0.18039216 0.18039216 0.18039216 ... 0.18431373 0.18431373 0.18823529]
 ...
 [0.22352941 0.23137255 0.23921569 ... 0.50588235 0.42745098 0.3254902 ]
 [0.2        0.2        0.20392157 ... 0.5372549  0.45490196 0.3254902 ]
 [0.18039216 0.18431373 0.18431373 ... 0.56862745 0.45882353 0.31764706]]


3.資料整併，並將訓練與測試分割

In [7]:
# train = gray_ok2.append(gray_ng1)
train = np.concatenate((gray_ok1,gray_ng1),axis=0)
target = np.concatenate((img_ok1_label,img_ng1_label),axis=0)
train2 = np.concatenate((gray_ok2,gray_ng2), axis=0)
target2 = np.concatenate((img_ok2_label,img_ng2_label),axis=0)

# target = img_ok1_label.append(img_ng1_label)

print(train.shape)
print(target.shape)
print(train2.shape)
print(target2.shape)

(1927, 112, 160)
(1927, 2)
(480, 112, 160)
(480, 2)


In [8]:
X_train1,  X_test1, y_train1, y_test1 = train_test_split(train, target, test_size=0.7)
X_train2,  X_test2, y_train2, y_test2 = train_test_split(train2, target2, test_size=0.5)

print(X_train1.shape, X_train2.shape)
print(X_test1.shape, X_test2.shape)
print(y_train1.shape, y_train2.shape)
print(y_test1.shape, y_test2.shape)

X_train = np.concatenate((X_train1,X_train2),axis=0)
y_train = np.concatenate((y_train1,y_train2),axis=0)
X_test = np.concatenate((X_test1,X_test2),axis=0)
y_test = np.concatenate((y_test1,y_test2),axis=0)


print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)






(578, 112, 160) (240, 112, 160)
(1349, 112, 160) (240, 112, 160)
(578, 2) (240, 2)
(1349, 2) (240, 2)
(818, 112, 160)
(818, 2)
(1589, 112, 160)
(1589, 2)


4.調整資料形狀

In [9]:
X_train = np.reshape(X_train, (818, 112, 160,1))
X_test = np.reshape(X_test, (1589, 112, 160,1))
print(X_train.shape)
print(X_test.shape)


(818, 112, 160, 1)
(1589, 112, 160, 1)


## 建造並訓練模型

In [10]:
model = Sequential()

input_shape =[112, 160,1]

model.add(Conv2D(input_shape = input_shape,
                 filters = 5,
                 kernel_size = (5,5),
                 padding = 'same',
                 activation = 'relu',
                 ))
model.add(MaxPooling2D(
                       pool_size = (2,2)
                       ))
model.add(Dropout(0.25))
model.add(Conv2D(filters = 10,
                 kernel_size = (5,5),
                 padding = 'same',
                 activation = 'relu'
                 ))
model.add(MaxPooling2D(
                       pool_size = (2,2)
                       ))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(
                units = 10,
                activation = 'relu'
                ))

model.add(Dense(
                units = 2,
                activation = 'softmax'
                ))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [11]:
train_history = model.fit(X_train,y_train, batch_size=32, validation_split=0.1,verbose=1,epochs=25)   #epochs ~ 25

Train on 736 samples, validate on 82 samples
Epoch 1/25
736/736 [==============================] - 10s 13ms/step - loss: 0.5940 - acc: 0.7174 - val_loss: 0.7016 - val_acc: 0.4634
Epoch 2/25
736/736 [==============================] - 9s 13ms/step - loss: 0.2840 - acc: 0.9307 - val_loss: 0.4453 - val_acc: 0.7927
Epoch 3/25
736/736 [==============================] - 9s 13ms/step - loss: 0.1575 - acc: 0.9470 - val_loss: 0.2989 - val_acc: 0.8780
Epoch 4/25
736/736 [==============================] - 9s 13ms/step - loss: 0.0820 - acc: 0.9728 - val_loss: 0.2240 - val_acc: 0.9146
Epoch 5/25
736/736 [==============================] - 9s 13ms/step - loss: 0.0532 - acc: 0.9837 - val_loss: 0.1149 - val_acc: 0.9634
Epoch 6/25
736/736 [==============================] - 9s 13ms/step - loss: 0.0322 - acc: 0.9932 - val_loss: 0.1196 - val_acc: 0.9634
Epoch 7/25
736/736 [==============================] - 9s 13ms/step - loss: 0.0224 - acc: 0.9918 - val_loss: 0.0794 - val_acc: 0.9634
Epoch 8/25
736/736 [===

## 驗證模型

In [12]:
# predict = model.predict(X_test)
model.evaluate(X_test,y_test,verbose=1,batch_size=32)

1589/1589 [==============================] - 11s 7ms/step


[0.0032901010832698317, 0.9993706733794839]

## 分析錯誤成因

1. 依據softmax特性找出'判定錯誤'與'信心低'的資料

In [38]:
predict = model.predict(X_test)
print(len(X_test))
err_idx_ng=[]
err_idx_ok=[]
err_value_ng=[]
err_value_ok=[]
for i in range(len(y_test)):
    if y_test[i][0] - predict[i][0]>0.5:
        err_idx_ng.append(i)
        err_value_ng.append(predict[i][0])
    elif y_test[i][0] - predict[i][0]< -0.5:
        err_idx_ok.append(i)
        err_value_ok.append(predict[i][0])
print('----------------error---------------')
print('ng but not found:',err_idx_ng)
print('ng but not found:',err_value_ng)

print('ok but predict error:',err_idx_ok)
print('ok but predict error:',err_value_ok)
print('----------------error---------------')
print('\n','\n')

idx_ok=[]
idx_ng=[]
value_ok=[]
value_ng=[]

for i in range(len(y_test)):
    if predict[i][0]>0.5 and predict[i][0]<0.55:
        idx_ok.append(i)
        value_ok.append(predict[i][0])
    elif predict[i][0]< 0.5 and predict[i][0]>0.45:
        idx_ng.append(i)
        value_ng.append(predict[i][0])
print('--------------confidency---------------')
print('ng confidency low:',idx_ok)
print('ng confidency low:',value_ok)

print('ok confidency low:',idx_ng)
print('ok confidency low:',value_ng)
print('--------------confidency---------------')

# predict

1589
----------------error---------------
ng but not found: []
ng but not found: []
ok but predict error: [1430]
ok but predict error: [0.5909069]
----------------error---------------

 

--------------confidency---------------
ng confidency low: []
ng confidency low: []
ok confidency low: []
ok confidency low: []
--------------confidency---------------


2. 將錯誤圖片秀出

In [39]:
for err in err_idx_ng:
    cv2.imshow('img'+str(err),X_test[err])
for err in err_idx_ok:
    cv2.imshow('img'+str(err),X_test[err])
for idx in idx_ok:
    cv2.imshow('img'+str(idx),X_test[idx])
for idx in idx_ng:
    cv2.imshow('img'+str(idx),X_test[idx])
    
cv2.waitKey(0)
cv2.destroyAllWindows()